// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPBSYB8v4T5sdDcQmqTUE04x1QWhqXleA',
    appId: '1:472769013189:web:a678b7d32bf394abc257ac',
    messagingSenderId: '472769013189',
    projectId: 'grupo-insight-app',
    authDomain: 'grupo-insight-app.firebaseapp.com',
    storageBucket: 'grupo-insight-app.firebasestorage.app',
    measurementId: 'G-FCCGCFP2BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqsnVaZMnZSOLxxPiei7BPSoP2bSaxnDo',
    appId: '1:472769013189:android:edeb128d4a2f9c40c257ac',
    messagingSenderId: '472769013189',
    projectId: 'grupo-insight-app',
    storageBucket: 'grupo-insight-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLX1QbYvfp6nGBdFekhviQLZ4CpinxA3Y',
    appId: '1:472769013189:ios:8f2a561e190af4dfc257ac',
    messagingSenderId: '472769013189',
    projectId: 'grupo-insight-app',
    storageBucket: 'grupo-insight-app.firebasestorage.app',
    iosClientId: '472769013189-q1c415dauv936mbkpg1ue48vtb9iubad.apps.googleusercontent.com',
    iosBundleId: 'com.example.consultorioPsicologiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLX1QbYvfp6nGBdFekhviQLZ4CpinxA3Y',
    appId: '1:472769013189:ios:8f2a561e190af4dfc257ac',
    messagingSenderId: '472769013189',
    projectId: 'grupo-insight-app',
    storageBucket: 'grupo-insight-app.firebasestorage.app',
    iosClientId: '472769013189-q1c415dauv936mbkpg1ue48vtb9iubad.apps.googleusercontent.com',
    iosBundleId: 'com.example.consultorioPsicologiaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPBSYB8v4T5sdDcQmqTUE04x1QWhqXleA',
    appId: '1:472769013189:web:34e4021adf7f21e7c257ac',
    messagingSenderId: '472769013189',
    projectId: 'grupo-insight-app',
    authDomain: 'grupo-insight-app.firebaseapp.com',
    storageBucket: 'grupo-insight-app.firebasestorage.app',
    measurementId: 'G-DD23RTZGKV',
  );
}
